# Generated by Django 4.2.4 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=30)),
            ],
        ),
    ]
