# Generated by Django 4.2.4 on 2023-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_de_precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_excel/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
